### ISSUE TITLE
Headers overlapping when resizing window

### ISSUE THREAD

**Issue by bengiv** [T-x-T/dukatia#78]
https://github.com/T-x-T/dukatia/assets/67504107/511c57c9-6a55-422a-b4f4-12e748d9a6de

last shown view also relates on https://github.com/T-x-T/dukatia/issues/77 cuz overlapping cuz of headers not being wide enough when window is too small

**Comment by T-x-T** [comment]
I cant watch the video, can you maybe upload it to discord and post link please?

**Comment by T-x-T** [comment]
it loaded as soon as I posted my comment lol :(

**Comment by T-x-T** [comment]
fixed in 0.20.1
