### ISSUE TITLE
When resetting password from current logged in user, dukatia says that i cant disable myself

### ISSUE THREAD

**Issue by bengiv** [T-x-T/dukatia#83]
<img width="431" alt="image" src="https://github.com/T-x-T/dukatia/assets/67504107/8430fbe0-8f42-40dd-8621-0f89e7c11560">

I know that you can update the password of the current user by using the 'Update Password' field, but when you try it the other way, I think its a bit wrong to say that it cant disable the current account. I would rather say that you can't change the password that way or remove the option itself from the current user. Resetting the password for other users works of course.

**Comment by T-x-T** [comment]
fixed in version 0.20.1
