### ISSUE TITLE
users table on settings page is way tooooo wide

### ISSUE THREAD

**Issue by T-x-T** [T-x-T/dukatia#92]

**Comment by bengiv** [comment]
Yea just wanted to create an issue for that, titled "Users in settings is trying to recreate wide putin meme"

**Comment by T-x-T** [comment]
Transactions in current Period table in a budget detail page is also toooooo wide

**Comment by T-x-T** [comment]
fixed in 0.21.0 by adding new property to CustomTable configuration to allow opting out of the fixed table layout
